### ISSUE TITLE
NVDA Remote server keeps crashing on Ubuntu 21.10

### ISSUE THREAD

**Issue by KevanGP** [jmdaweb/NVDARemoteServer#41]
It should be noted that I'm not using the default port of 6837... Log is below.

Traceback (most recent call last):
  File "/usr/share/NVDARemoteServer/server.py", line 284, in accept_new_connection
    client_sock = ssl.wrap_socket(client_sock, keyfile=options.keyfile, certfile=options.certfile, server_side=True)
  File "/usr/lib/python3.9/ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1129)

**Comment by jmdaweb** [comment]
Hi,
This error is related to the SSL certificate. Which certificate are you using? Can you paste the relevant lines from the configuration file?
Regards.

**Comment by KevGP** [comment]
Hi,

Sorry for just getting back, must have not seen the reply until now.
I decided to reinstall my Linode earlier, however the exact same thing keeps happening. Below I have the certFile line from the config, followed by the new log.

certfile=/usr/share/NVDARemoteServer/server.pem


Traceback (most recent call last):
  File "/usr/share/NVDARemoteServer/server.py", line 284, in accept_new_connection
    client_sock = ssl.wrap_socket(client_sock, keyfile=options.keyfile, certfile=options.certfile, server_side=True)
  File "/usr/lib/python3.10/ssl.py", line 1441, in wrap_socket
    return context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997)

I did use the NVDARemoteCertificate utility before turning it on, and hope I correctly set the location in the config file.

**Comment by KevGP** [comment]
Sorry the preceeding happened when I didn't change the config file and set the certificate location.
When I set the certificate to the specific location, the server won't even accept any new connections at all.
Traceback (most recent call last):
  File "/usr/share/NVDARemoteServer/server.py", line 284, in accept_new_connection
    client_sock = ssl.wrap_socket(client_sock, keyfile=options.keyfile, certfile=options.certfile, server_side=True)
  File "/usr/lib/python3.10/ssl.py", line 1438, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory

I checked the config, and also my actual system, I can find the .pem and the location looks correct. Weird.
